### ISSUE TITLE
Image Cacheing Mixin

### ISSUE THREAD

**Issue by zspecza** [jenius/axis#100]
So, I was thinking...

There is a technique whereby one can achieve a relatively simple means of "preloading" images through the use of CSS alone, and it is considerably well-supported given that all it requires feature-wise is pseudo-elements.

The technique is to simply create a pseudo-element on a top level node (e.g. the `body` tag), set it to `display: none` and then store a space-separated list of `url(path/to/image)`s in the `content` property, like so:

``` css
.first-image {
  background: url("../img/image1.png");
}

.second-image {
  background: url("../img/image2.png");
} 

body:after {
  display: none;
  content: url("../img/image1.png") url("../img/image2.png");
}
```

Though it may not seem obvious at first, this is quite a useful technique, because it technically enables the browser to cache _every_ image on a website on the first page load, no matter what page the image does or does not display on.

This means that if Bobby Jenkins visits a website with this code for the first time, he'll wait for the page to load, but every page he visits after that will already have every image (that was set in CSS) pre-loaded and cached, so he won't be waiting on them to load when he browses the site further.

The only two drawbacks to this technique is that: 
1. it requires maintaining a long list of images
2. the `body:after` declarations need to be at the bottom of the stylesheet or it will cause a cascade failure

The good news is, because Stylus has transparent mixins, we can cache any image the user enters into their stylesheet in an array automatically, and then they can call a mixin that outputs all the images for them, taking the pain of maintenance away:

```
// initialize empty "array"
image-cache = null

// overwrite url() to cache any images not in the "array" already
// then revert back to it's original use
url(s)
  push(image-cache, s('url(%s)', s)) unless s in image-cache
  return 'url(%s)' % s

// mixin that outputs the image cache script
cache-images()
  body:after
    display: none
    content: image-cache

.element-1
  background: url('img/image1.png')

.element-2
  background: url('img/image2.png')

cache-images()
```

This results in the following CSS:

``` css
.element-1 {
  background: url('img/image1.png');
}
.element-2 {
  background: url('img/image2.png');
}
body:after {
  display: none;
  content: url('img/image1.png') url('img/image2.png');
}
```

Does this sound awesome or what? Before implementing it, though - I wanted to get your opinion @jenius - does this kind of mixin belong in Axis?
