### ISSUE TITLE
normalize-css produces invalid css output

### ISSUE THREAD

**Issue by zspecza** [jenius/axis#129]
``` css
article: , aside, details, figcaption, figure, footer, header, hgroup, main, nav, section;
summary {
  display: block;
}
```

wat
