### ISSUE TITLE
Lost Grid conflict

### ISSUE THREAD

**Issue by zuzust** [jenius/axis#222]
Using both Axis and Lost grid system results in lost's clearfix utility not being processed.

**gulp task**

```javascript
gulp.task('compile:styles', function() {
  var stylus = require('gulp-stylus');
  var postcss = require('gulp-postcss');
  var axis = require('axis');
  var lost = require('lost');

  var processors = [lost()];
  var plugins = [axis()];

  return gulp.src('./src/assets/styles/main.styl')
    .pipe(stylus({use: plugins}))
    .pipe(postcss(processors))
    .pipe(gulp.dest('./site/assets/styles'))
});
```

**main.styl**

```stylus
@charset 'UTF-8'

section
  lost-utility: clearfix

article
  lost-column: 1/3
```

**main.css**

```css
@charset 'UTF-8';
article {
  width: calc(99.99% * 1/3 - (30px - 30px * 1/3));
}
article:nth-child(n){
  float: left;
  margin-right: 30px;
  clear: none;
}
article:last-child{
  margin-right: 0;
}
article:nth-child(3n){
  margin-right: 0;
}
article:nth-child(3n + 1){
  clear: left;
}
```

When `var plugins = [];` then:

**main.css**

```css
@charset 'UTF-8';
section {
  *zoom: 1;
}
section:before{
  content: '';
  display: table;
}
section:after{
  content: '';
  display: table;
  clear: both;
}
article {
  width: calc(99.99% * 1/3 - (30px - 30px * 1/3));
}
article:nth-child(n){
  float: left;
  margin-right: 30px;
  clear: none;
}
article:last-child{
  margin-right: 0;
}
article:nth-child(3n){
  margin-right: 0;
}
article:nth-child(3n + 1){
  clear: left;
}
```
