### ISSUE TITLE
Rewrite of grid-area values

### ISSUE THREAD

**Issue by BriceG-D** [jenius/axis#337]
Using this sample code
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas#Example

### Actual behaviour
Axis does rename the `grid-area: nav;` to `navigation` which does break everything.
``` css
#page > nav {
  grid-area: nav;
  background-color: #ffa08c;
}
```

### Expected behaviour
It should not touch the name of the `grid-area`
