### ISSUE TITLE
media() mixin results in duplicate `zoom` property

### ISSUE THREAD

**Issue by zspecza** [jenius/axis#96]
The `media()` mixin adds `zoom: 1` to the direct child element in [utilities.styl#L221](https://github.com/jenius/axis/blob/master/axis/utilities.styl#L221), even though it calls `inline-block()` [beforehand](https://github.com/jenius/axis/blob/master/axis/utilities.styl#L219), which has it's own `zoom: 1` property declared [here](https://github.com/jenius/axis/blob/master/axis/utilities.styl#L188). It basically outputs slightly duplicate CSS:

``` css
.selector {
  overflow: hidden;
  zoom: 1;
}
.selector > * {
  display: -moz-inline-stack;
  display: inline-block;
  vertical-align: baseline;
  zoom: 1;
  *display: inline;
  *vertical-align: auto;
  overflow: hidden;
  zoom: 1;
}
.selector > *:first-child {
  float: left;
  margin-right: 10px;
}
.selector > *:nth-child(3) {
  float: right;
  margin-left: 10px;
}
```
